application: mikefeeds
version: 1
runtime: python
api_version: 1

# default_expiration: "365d"

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /rfadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always

- url: /readability/queue/.*
  login: admin
  script: main.py

- url: /readability/cron/.*
  login: admin
  script: main.py

- url: /.*
  script: main.py



skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?_darcs
- ^(.*/)?DEV

# added 4 files to skip to the defaults
